// Generated by i18next-cli — review and adapt to your project's needs.
// You may need to install dependencies: npm install i18next
//
// Other translation loading approaches:
//   • Static imports or bundled JSON: https://www.i18next.com/how-to/add-or-load-translations
//   • Lazy-load from a server: https://github.com/i18next/i18next-http-backend
//   • Manage translations with your team via Locize: https://www.locize.com
//     (see i18next-locize-backend: https://github.com/locize/i18next-locize-backend)
import i18next from 'i18next'
import enTranslation from '../public/locales/en/translation.json'
import deTranslation from '../public/locales/de/translation.json'
import frTranslation from '../public/locales/fr/translation.json'
import esTranslation from '../public/locales/es/translation.json'
import itTranslation from '../public/locales/it/translation.json'
import jaTranslation from '../public/locales/ja/translation.json'

i18next.init({
    returnEmptyString: false, // allows empty string as valid translation
    // lng: 'ja', // or add a language detector to detect the preferred language of your user
    fallbackLng: 'en',
    defaultNS: 'translation',
    resources: {
      en: { translation: enTranslation },
      de: { translation: deTranslation },
      fr: { translation: frTranslation },
      es: { translation: esTranslation },
      it: { translation: itTranslation },
      ja: { translation: jaTranslation },
    },
  })

export default i18next
